import {
  Activity,
  Baby,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Camera,
  Car,
  Code2,
  Coffee,
  Compass,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Map,
  MapPin,
  Mountain,
  Music,
  Palette,
  PawPrint,
  PiggyBank,
  Plane,
  Rocket,
  Ship,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  TrainFront,
  Trees,
  Users,
  Utensils,
  Wallet,
} from "lucide-react";

export const SPACE_ICONS = [
  { id: "home", label: "Home", icon: House },
  { id: "users", label: "Family & Friends", icon: Users },
  { id: "heart", label: "Relationships", icon: Heart },
  { id: "baby", label: "Family", icon: Baby },
  { id: "paw", label: "Pets", icon: PawPrint },

  { id: "briefcase", label: "Work", icon: Briefcase },
  { id: "building", label: "Business", icon: Building2 },
  { id: "laptop", label: "Technology", icon: Laptop },
  { id: "code", label: "Development", icon: Code2 },

  { id: "book", label: "Study", icon: BookOpen },
  { id: "graduation", label: "University", icon: GraduationCap },
  { id: "brain", label: "Learning", icon: Brain },

  { id: "dumbbell", label: "Fitness", icon: Dumbbell },
  { id: "activity", label: "Activity", icon: Activity },
  { id: "health", label: "Health", icon: HeartPulse },
  { id: "bike", label: "Cycling", icon: Bike },

  { id: "plane", label: "Travel", icon: Plane },
  { id: "car", label: "Road Trip", icon: Car },
  { id: "train", label: "Train", icon: TrainFront },
  { id: "ship", label: "Sea Travel", icon: Ship },
  { id: "map", label: "Explore", icon: Map },
  { id: "pin", label: "Places", icon: MapPin },
  { id: "compass", label: "Adventure", icon: Compass },
  { id: "mountain", label: "Outdoor", icon: Mountain },
  { id: "trees", label: "Nature", icon: Trees },

  { id: "camera", label: "Photography", icon: Camera },
  { id: "music", label: "Music", icon: Music },
  { id: "gaming", label: "Gaming", icon: Gamepad2 },
  { id: "palette", label: "Creative", icon: Palette },
  { id: "coffee", label: "Lifestyle", icon: Coffee },
  { id: "food", label: "Food", icon: Utensils },

  { id: "shopping", label: "Shopping", icon: ShoppingBag },
  { id: "wallet", label: "Finance", icon: Wallet },
  { id: "savings", label: "Savings", icon: PiggyBank },

  { id: "sun", label: "Personal", icon: Sun },
  { id: "star", label: "Goals", icon: Star },
  { id: "sparkles", label: "Ideas", icon: Sparkles },
  { id: "rocket", label: "Projects", icon: Rocket },
] as const;

export type SpaceIcon = (typeof SPACE_ICONS)[number]["id"];
